# Generated by Django 5.2.14 on 2026-06-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=30, null=True, unique=True, verbose_name="닉네임"
            ),
        ),
    ]
