# Generated by Django 5.2.14 on 2026-06-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/", verbose_name="프로필 사진"
            ),
        ),
    ]
