# Generated by Django 5.2.14 on 2026-06-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="scolded_message_ids",
            field=models.JSONField(
                blank=True, default=list, verbose_name="나리에게 혼난 멘트 id 목록"
            ),
        ),
    ]
