# Generated by Django 5.2.14 on 2026-06-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_scolded_message_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="chat_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="나리와 대화한 횟수"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="night_chat_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="심야(00~06시) 대화 횟수"
            ),
        ),
    ]
