# Generated by Django 5.2.14 on 2026-05-15 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='장소명')),
                ('category', models.CharField(choices=[('historic', '역사 유적'), ('museum', '박물관·미술관'), ('park', '공원·자연'), ('palace', '궁궐·사찰'), ('culture', '문화 시설'), ('etc', '기타')], max_length=20, verbose_name='카테고리')),
                ('region', models.CharField(choices=[('seoul', '서울'), ('gyeonggi', '경기')], max_length=20, verbose_name='지역')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='위도')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='경도')),
                ('is_indoor', models.BooleanField(default=False, verbose_name='실내 여부')),
                ('is_active', models.BooleanField(default=False, verbose_name='동적 장소 여부')),
                ('open_time', models.CharField(blank=True, max_length=100, verbose_name='운영 시간')),
                ('entrance_fee', models.PositiveIntegerField(default=0, verbose_name='입장료 (원)')),
                ('description', models.TextField(blank=True, verbose_name='장소 설명')),
                ('image_url', models.URLField(blank=True, verbose_name='대표 이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '문화 장소',
                'verbose_name_plural': '문화 장소 목록',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='테마명')),
                ('era', models.CharField(choices=[('three_kingdoms', '삼국시대'), ('goryeo', '고려시대'), ('joseon', '조선시대'), ('japanese', '일제강점기'), ('modern', '현대')], max_length=20, verbose_name='시대 구분')),
                ('description', models.TextField(blank=True, verbose_name='테마 설명')),
            ],
            options={
                'verbose_name': '테마',
                'verbose_name_plural': '테마 목록',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], verbose_name='별점')),
                ('content', models.TextField(verbose_name='리뷰 내용')),
                ('image', models.URLField(blank=True, verbose_name='리뷰 이미지 (S3 URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='culture.place', verbose_name='장소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='코스명')),
                ('mode', models.CharField(choices=[('distance', '거리 기준'), ('theme', '테마 기준'), ('time', '소요시간 기준')], max_length=20, verbose_name='추천 모드')),
                ('total_distance', models.PositiveIntegerField(default=0, verbose_name='총 거리 (m)')),
                ('total_time', models.PositiveIntegerField(default=0, verbose_name='총 소요시간 (분)')),
                ('is_shared', models.BooleanField(default=False, verbose_name='커뮤니티 공유 여부')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='좋아요 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='생성 유저')),
            ],
            options={
                'verbose_name': '동선 코스',
                'verbose_name_plural': '동선 코스 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='순서')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.place', verbose_name='장소')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.route', verbose_name='코스')),
            ],
            options={
                'verbose_name': '코스 장소 순서',
                'ordering': ['order'],
                'unique_together': {('route', 'order')},
            },
        ),
        migrations.AddField(
            model_name='route',
            name='places',
            field=models.ManyToManyField(related_name='routes', through='culture.RoutePlace', to='culture.place', verbose_name='장소 목록'),
        ),
        migrations.AddField(
            model_name='place',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='culture.theme', verbose_name='테마'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='culture.place', verbose_name='장소')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='culture.route', verbose_name='코스')),
            ],
            options={
                'verbose_name': '북마크',
                'verbose_name_plural': '북마크 목록',
                'unique_together': {('user', 'place'), ('user', 'route')},
            },
        ),
    ]
