# Generated by Django 5.2.14 on 2026-05-29 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='culture.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '코스 댓글',
                'verbose_name_plural': '코스 댓글 목록',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='culture.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '코스 좋아요',
                'verbose_name_plural': '코스 좋아요 목록',
                'unique_together': {('user', 'route')},
            },
        ),
    ]
