# Generated by Django 5.2.14 on 2026-06-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culture", "0002_routecomment_routelike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="category",
            field=models.CharField(
                choices=[
                    ("historic", "역사 유적"),
                    ("museum", "박물관·미술관"),
                    ("palace", "궁궐·사찰"),
                ],
                max_length=20,
                verbose_name="카테고리",
            ),
        ),
    ]
