# Generated by Django 5.2.14 on 2026-06-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culture", "0003_alter_place_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="website",
            field=models.URLField(blank=True, verbose_name="공식 홈페이지 URL"),
        ),
    ]
