# Generated by Django 5.2.14 on 2026-06-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culture", "0004_add_website_to_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="transport_mode",
            field=models.CharField(
                choices=[
                    ("walk", "도보"),
                    ("bike", "자전거"),
                    ("transit", "대중교통"),
                    ("car", "자동차"),
                    ("train", "기차"),
                ],
                default="car",
                max_length=20,
                verbose_name="이동수단",
            ),
        ),
    ]
