# Generated by Django 5.2.14 on 2026-06-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culture", "0005_add_transport_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="is_footprint",
            field=models.BooleanField(
                default=False, verbose_name="여행 완료 시 자동 기록된 발자취 여부"
            ),
        ),
    ]
