# Generated by Django 5.2.14 on 2026-06-23 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("culture", "0006_route_is_footprint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="image",
        ),
    ]
