# Generated by Django 5.2.14 on 2026-06-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culture", "0007_remove_review_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="path_data",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="실제 이동 경로 좌표 (생성 시점에 1회 계산해 저장)",
            ),
        ),
    ]
